apiVersion: apps/v1
kind: Deployment
metadata:
  name: Whisperer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Whisperer
  template:
    metadata:
      labels:
        app: Whisperer
    spec:
      containers: # Correctly indented
        - name: nginx-container
          image: nginx
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 256Mi
              cpu: '0.2'
