apiVersion: v1
kind: Service
metadata:
  name: Whisperer
  namespace: Whisperer # Add a specific namespace here
spec:
  selector:
    app: Whisperer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
